name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      # As an error occurs, disable the following code for now
      # - name: Lint CSS
      #   run: pnpm lint:css

      - name: Format check
        run: pnpm format

      # Create a pull request if there are any changes
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Fix format and lint issues"
          body: "Update code format and lint issues automatically"
          branch: ${{ github.ref }}
          commit-message: "fix format and lint issues"

      - run: pnpm build
