name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      # As an error occurs, disable the following code for now
      # - name: Lint CSS
      #   run: pnpm lint:css

      - name: Format check
        run: pnpm format

      - uses: stefanzweifel/git-auto-commit-action@v5

      - run: pnpm build
